<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(RunConfiguration)' == 'http' " />
  <PropertyGroup Condition=" '$(RunConfiguration)' == 'https' " />
  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="7.0.19" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="7.0.19" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="7.0.19">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="7.0.19">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="System.Data.SqlClient" Version="4.8.6" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Forms" Version="6.0.31" />
    <PackageReference Include="PowerDeploy.PackageManagerExtension" Version="0.6.2" />
    <PackageReference Include="WisdomCloud.KendoUI" Version="1.7.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.ViewFeatures" Version="2.2.0" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Controllers\" />
    <None Remove="Model\" />
    <None Remove="Data\" />
    <None Remove="Model\DTO\" />
    <None Remove="Model\Entities\" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Controllers\" />
    <Folder Include="Model\" />
    <Folder Include="Data\" />
    <Folder Include="Model\DTO\" />
    <Folder Include="Model\Entities\" />
    <Folder Include="wwwroot\" />
  </ItemGroup>
  <ItemGroup>
    <Compile Condition=" '$(EnableDefaultCompileItems)' == 'true' " Update="Model\Entities\NYO_SosyalYardimModel.cs">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <Content Remove="wwwroot\" />
  </ItemGroup>
</Project>
